### PR TITLE
on 4th time this check is evaluated, it throws an undefined

### PR DESCRIPTION
**Pull request by minoseah629**
image

# 1 

image

# 2
image

# 3
image

# 4
image

### CODE REVIEW

**Comment by thim81** [comment]
Hi @minoseah629 

Thanks for reporting this. 

Could you share which version of K6 you are using?

**Comment by minoseah629** [comment]
ill share this was a problem prior to running any k6 command: 

k6.exe v0.51.0 (commit/33d3caa7d1, go1.22.3, windows/amd64)

**Comment by thim81** [comment]
Would it be possible to share how to reproduce the issue? 
I want to figure why exec becomes undefined.

**Comment by thim81** [comment]
Your PR looks good since it improves the JavaScript safety with the optional chaining, but it is strange that exec becomes undefined.

**Comment by minoseah629** [comment]
i cannot share the exact postman collection json.  I have exported my postman collection yesterday.  this is what I observed:

1. A good test that has an exec but with an list of 1 string that's empty.
image

2. Postman has been updated to incorporate a package concept: https://learning.postman.com/docs/tests-and-scripts/write-scripts/package-library/

3. The specific request I see is somehow the usage of packages (even though the script is empty and not using a package),  the script does not have an empty exec as expected:

image
image

4. This specific request is the only one like this.

**Comment by thim81** [comment]
@minoseah629 Thanks again for sharing this detailed info and the screenshots. It will allow us to rebuild a Postman collection to reproduce the mentioned cases and add some tests to cover this from the future.

Give me a bit of time to process this all and reproduce it, that will allow your PR to land properly and covered.

**Comment by minoseah629** [comment]
sounds good. 

sorry for not generating unit tests. not as good with javascript compared to c# experience.

**Comment by thim81** [comment]
@minoseah629 I was not expecting unit tests, I'm already very happy with all your input and the PR.

**Comment by thim81** [comment]
I have not been able to reproduce it, but the PR changes are useful for a safer JS.

Did it solve your problem?

**Comment by thim81** [comment]
hi @minoseah629 

We just released v1.10.0 of postman-to-k6 cli.
It includes your PR and some more improvements and additional tests (WIP).

Thanks for your contribution. Let me know if your issue is resolved or still occurring.

**Pull request merged**
